steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--pull'
      - '-f'
      - '${_DOCKERFILE}'
      - '-t'
      - '${_IMAGE}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE}'

images:
  - '${_IMAGE}'

serviceAccount: '${_BUILDER_SA}'

options:
  machineType: 'E2_HIGHCPU_32'
  logging: 'CLOUD_LOGGING_ONLY'
  dynamicSubstitutions: true

timeout: '7200s'
